### ISSUE TITLE
データの取得先を表示

### ISSUE THREAD

**Issue by takayashibagaki** [Stop-COVID19-Nagano/covid19#1]
## 改善詳細 / Details of Improvement
- データの出所をリンクさせたい。

東京都版はこんな感じでリンクを張り付けてます。
<img width="143" alt="コメント 2020-03-16 122450" src="https://user-images.githubusercontent.com/24749743/76720848-5869eb00-6781-11ea-91d7-5b29c4103810.png">

**Comment by tsuka39** [comment]
ありがとうございます！
データの出所、記載したいですね。

17日に長野県のコロナ関連のページにオープンデータと表記で、CSVファイルのリンクが追加されていました。
でも、まだ「長野県オープンデータサイト」に掲載されていない。
CSVは日付ごとにファイル名が変わるので、都度修正はちょっとシンドそうですね、、、

何か良い方法あったらご提案お願いします。
私も考えてみます！！

**Comment by wataruoguchi** [comment]
@takayashibagaki @tsuka39 

ファイル直接へのリンクは現実的ではないのでこちらにリンクを貼れば良いかと思います！
https://www.pref.nagano.lg.jp/joho/kensei/tokei/johoka/opendata/
