### ISSUE TITLE
i18n の canonical な URL について

### ISSUE THREAD

**Issue by Hiroaki-Inomata** [Stop-COVID19-Nagano/covid19#101]
すみません。貴リポジトリを眺めていて気がついたのですが、
layouts/default.vue で

head(): MetaInfo {
    const { htmlAttrs } = this.$nuxtI18nSeo()
    return {
      htmlAttrs,
      link: [
        {
          rel: 'canonical',
          href: `https://stopcovid19.metro.tokyo.lg.jp${this.$route.path}`
        }
      ]
    }
  }

と canonical が東京のままになってませんか？

私は自サイトでは修正したんですが、ここらへん詳しくないので何が適当なローカライズなのかわかりません。

**Comment by kikd** [comment]
検索エンジンでマイナスの評価を受ける場合があるので、修正しているのが正解だと思います。

**Comment by kikd** [comment]
_card.vueも同様に修正します。
