### ISSUE TITLE
「お子様をお持ちの皆様へ」 3.の見出し表示がおかしい

### ISSUE THREAD

**Issue by kikd** [Stop-COVID19-Nagano/covid19#105]
## 起こっている問題 / The Problem
- 「お子様をお持ちの皆様へ」 3.の見出しが"[object Object]"になっている

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/5682821/78955897-a2918280-7b1b-11ea-82b0-a728b292e346.png)

## 期待する見せ方・挙動 / Expected Behavior
- 3.の見出しが"その他"と表示される

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://nagano.stopcovid19.jp/parent を開く

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by ShinoharaTa** [comment]
原因特定しました。i18n対応に関連するものなので、私の方で見ます。

**Comment by kikd** [comment]
お願いします！
