### ISSUE TITLE
「最新のお知らせ」の日付フォーマットを見やすい形式にしたい

### ISSUE THREAD

**Issue by tsuka39** [Stop-COVID19-Nagano/covid19#11]
## 改善詳細 / Details of Improvement
- 「最新のお知らせ」の日付のフォーマットがmm/dd/yyyyで表示されているのを、yyyy/mm/ddに変更して見やすくしたい。

## スクリーンショット / Screenshot
![県内の最新感染動向___長野県_非公式_新型コロナウイルス感染症対策サイト](https://user-images.githubusercontent.com/23370404/77242708-a892f280-6c44-11ea-9319-4a67b8ee67c4.png)

## 期待する見せ方・挙動 / Expected behavior
現状　3/14/2020
　　↓
修正案　2020/3/14

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by bon2016** [comment]
これの修正が必要であればすぐにでもプルリク出来ます。

**Comment by bon2016** [comment]
そもそもですが、もとの東京では、データ自体の日付フォーマットが「YYYY/mm/dd」形式で統一されているようです。
ですので、このissueに対しては
1. データの日付形式を統一する
1. データの日付形式を気にせずに、「YYYY/mm/dd」形式で統一できる関数を用意する

以上、二通りの方法が考えられます。
関数を用意するのは簡単ですが、運用方法を東京に合わせるかどうかをまずは検討する必要があると思います。

**Comment by tsuka39** [comment]
@bon2016 
あ！なるほど！
news.jsonがそうなってるのですね。
ありがとうございます！
jsonファイルを修正します。
