### ISSUE TITLE
リダイレクトできない条件がある

### ISSUE THREAD

**Issue by ShinoharaTa** [Stop-COVID19-Nagano/covid19#114]
## 改善詳細 / Details of Improvement
以前実装したリダイレクトの設定に漏れがあり、ルート以外のURLにアクセスした場合はリダイレクトがされない

https://stop-covid19-nagano.netlify.com/about/
https://stop-covid19-nagano.netlify.com/link/

## 期待する見せ方・挙動 / Expected behavior
リダイレクトした上で、aboutなりlinkなりにアクセスできること

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kikd** [comment]
https://docs.netlify.com/routing/redirects/redirect-options/#splats
これが使えれば変更量少なめで済みそうですが、いかがでしょうか？

**Comment by ShinoharaTa** [comment]
そうですね、ワイルドカード指定していないので、いまは遷移できていない状況。
この方法であれば対応できます！

**Comment by kikd** [comment]
こちらのissueほったらかしにしてしまい申し訳ありません。。。:bow:

プルリクエストは作業途中の状態で発行しても構わないので、対応いただけると助かります！
(タイトルにWIPなどついていれば判断可能です)

**Comment by ShinoharaTa** [comment]
見てる余裕なくてほったらかしにしてしまいました。
時間見つけて後ほど対応します
