### ISSUE TITLE
本番環境の更新が反映されていない

### ISSUE THREAD

**Issue by kikd** [Stop-COVID19-Nagano/covid19#118]
## 起こっている問題 / The Problem
- 本番環境へのデプロイが反映されていないようです。。

## スクリーンショット / Screenshot

最終更新日時が14日で止まっているのと、Twitterのアイコンが追加できていません。
![image](https://user-images.githubusercontent.com/5682821/79431118-f3fead80-8004-11ea-80fe-5f688c7d0146.png)

* [dev版](https://dev-covid19-nagano.netlify.app/)では反映されています。
* masterブランチにはコードがマージされています。

## 期待する見せ方・挙動 / Expected Behavior
- 本番環境で最新版が表示される

## 起こっている問題の再現手段 / Steps to Reproduce
1.  [本番環境](https://nagano.stopcovid19.jp)にアクセスする

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kikd** [comment]
ページ情報がどっかでキャッシュされている・・・？

**Comment by ShinoharaTa** [comment]
データも14日から更新されていないようです。
ビルドエラーになっていないか、GitHub Actions？またはNetlify？の動作など見たほうがいいかもしれないです。

**Comment by ShinoharaTa** [comment]
Netlify側でエラーになっておりました。

```
2:06:09 PM: Build ready to start
2:06:11 PM: build-image version: 2dbd444fcdce00cf06325060a8238d5ae3e86774
2:06:11 PM: build-image tag: v3.3.7
2:06:11 PM: buildbot version: 134ec431c6a3ff76e87cc4dc34007fe13842272f
2:06:11 PM: Fetching cached dependencies
2:06:11 PM: Starting to download cache of 96.3MB
2:06:13 PM: Finished downloading cache in 2.541495362s
2:06:13 PM: Starting to extract cache
2:06:15 PM: Finished extracting cache in 1.550681419s
2:06:15 PM: Finished fetching cache in 4.118984898s
2:06:15 PM: Starting to prepare the repo for build
2:06:15 PM: Preparing Git Reference refs/heads/production
2:06:18 PM: Failing build: Failed to prepare repo
2:06:18 PM: failed during stage 'preparing repo': exit status 1
2:06:18 PM: Finished processing build request in 7.0850806s
```

報告までに。

**Comment by wataruoguchi** [comment]
"clear cache and deploy" で prod deploy publish できました。closing
