### ISSUE TITLE
オープンデータフォーマット変更に伴うデータ不整合

### ISSUE THREAD

**Issue by wataruoguchi** [Stop-COVID19-Nagano/covid19#122]
## 起こっている問題 / The Problem
- 長野県提供のオープンデータのファイルフォーマットが変えられている／変えられようとしている。
- このため、いくつか更新できていないデータがある。
- 4月27日からさらに新たなフォーマットを提供するとのこと。現行データの廃止を意味していると考えられる。

現時点の暫定的な変更に合わせてスクリプトを更新しても、また変えられてしまうため、今週は耐え忍ぼうと思います。
来週の日曜日（日本時間月曜日）に時間が取れるかと思うので、そこで新しいフォーマットに合わせた CSV -> JSON 変換スクリプトを書く予定です。
現行と全く異なるので、新しいリポジトリを作成予定です。リポジトリ作成し次第、このissueを移動することを考えています。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by KitazawaAtsushi** [comment]
小口さん、初めまして。
長野県ホームページを担当している県庁職員です。直接のコメントすみません。
開発についてやここでのルールなど無知でして、もしコメントが不適切であれば無視してください。

小口さんをはじめ開発のみなさま、素晴らしいサイトをつくっていただきありがとうございます。県の担当部局にはツカハラさんという方と連絡を取っていると聞きました。そのあたり飛ばして連絡しておりすみません。

今後（皆様に影響しそうな）県のHP関係の変更として
・明日CSVフォーマットを変える（と聞いています。正確には私はHP見直し作業を進めており、データ管理元は別部局になるため）
・CSVだけでなくHP上の情報を改めて整理している
・皆様になるべく負担のない改修にしたい
ということでコメントさせていただきました。

CSV以外でサイトに影響する可能性があるものとして
・「新着情報」→「重要なお知らせ」に名称変更する可能性あり
https://www.pref.nagano.lg.jp/hoken-shippei/kenko/kenko/kansensho/joho/corona.html
・一部アンカーが削除整理される可能性あり（例えば以下　#soudan）
https://www.pref.nagano.lg.jp/hoken-shippei/kenko/kenko/kansensho/joho/corona-soudan.html#soudan
このあたりは影響しますかね？

あと相談として
・陽性患者の属性一覧に、該当日プレスリリースへのリンクを掲載できないか（退院欄の右列など）
があります。CSVフォーマット変更で対応できるならば・・・

個人的には皆様のサイト素晴らしいなと思っていて、県HPに「公認」とかでリンクできればとてもいいのではないかと考えています（このあたりは担当部局や上の判断が必要ですが）。

突然のコメント＆長文すみません。
本当に対応ありがとうございます。

**Comment by wataruoguchi** [comment]
@KitazawaAtsushi こんにちは。週末にも関わらず、ご連絡いただきありがとうございます。

お問い合わせ頂いた二点の変更（新着情報、アンカー）については、変更に影響はありません。(CC:  @tsuka39 )

> ・陽性患者の属性一覧に、該当日プレスリリースへのリンクを掲載できないか（退院欄の右列など）
があります。CSVフォーマット変更で対応できるならば・・・

こちらについては「備考」欄に記載するのはいかがでしょう？
もし何らかの理由でそれが難しい場合、新しい項目を備考欄の後に追加しても良いかもしれません。
そちらから頂いたサンプルファイルの `test_count` のCSVも、総務省からのフォーマットの後に項目を追加していますね。
変更するタイミングでご連絡頂ければ、対応できます。

私たちも、県の職員の方々の負担を減らしながら有意義な情報を伝えられれば、と活動しています。

例えば、毎回グラフの画像ファイルを作って、サイトにアップロードして、というのも手間ですよね。こちらのサイトでも同じようなことをやっているので、画像をアップロードする代わりにこちらへのリンクを貼れれば、職員の方の手間を減らすことができるのでは、と考えています。

オープンデータを公表する、ということは、世界中のプログラマーに仕事を委任できる可能性がある、ということです。かくいう私も故郷の長野県のためにカナダからお手伝いさせて頂いています。

新しいことだらけで不慣れなことも多いかと思いますが、私は長野県がCOVID19のオープンデータを公表して頂いていることに大変感謝しています。ありがとうございます 🙏 

P.S. 今回だけでなく、オープンデータに関わることは、差し支えなければお気軽にご相談ください。そこらの受託系のソフトウェア業者よりいいアドバイスができると思います。

**Comment by KitazawaAtsushi** [comment]
@wataruoguchi さん、さっそくありがとうございます！
カナダから！地理的には遠く離れていますが、故郷を想うお気持ちは本当に近く感じます。ありがとうございます。

> こちらについては「備考」欄に記載するのはいかがでしょう？
→patientsファイルの備考欄に当該URLを記載する、ということですね。
　それならすぐに可能かと思いますので、担当部局に聞いています。

> 例えば、毎回グラフの画像ファイルを作って、サイトにアップロードして、というのも手間ですよね。
→おっしゃる通りです。いちいちパワポで作成して画像化してアップロードして・・・という作業が発生しています。内部的な会議にそのパワポを使うのでそれはそれで一石二鳥、という面もあるのですが、ウェブサイトとしては美しくないし手間もかかるしなので、皆様のサイトに誘導するor画面埋め込みで更新できたりするといいなぁと思っています。これも担当部局と相談して対応を試みてみます。

長野県のサイトはCMSが貧弱？というかで大変作りづらい、みづらいサイトだと思います（表すらも管理しづらい、YouTubeの動画すらも埋め込めないなど）。
そんな中で皆様にお力をいただいているのは本当に心強い限りです。

まったく差し支えませんので、今後も気軽に相談させてください。
いろいろご教示いただけるとありがたいです。

上記対応決まりましたら、また連絡させていただきます。
小口さんも休日にも関わらず、ご対応ありがとうございます。

**Comment by tsuka39** [comment]
@KitazawaAtsushi 　さん、こんにちは！

いつもお世話になっております。塚原です。
県庁の方から直接Githubにコメントいただけて、嬉しくて感動しています、、
あまりに嬉しすぎて、それを伝えたくてコメントしてしまいました！

こんなことやってみたい、こんなことできない？などありましたら、相談でもご要望でもご指摘でも、ぜひぜひ、コメントやissueの登録してくださいませ。
窓口になっていただいている方から、メールをいただくでも構いません。
また、私達からも相談などさせていただくこともあると思いますので、その時はどうぞよろしくお願いいたします。

気軽にお互い相談できる関係になれると、長野県を想う皆様により良い情報発信ができると思っております。
今後ともどうぞよろしくお願いします！

**Comment by KitazawaAtsushi** [comment]
@tsuka39 　塚原さん、いつも伊東がお世話になっています。
こちらこそ、とても素晴らしいサイトを皆さんで立ち上げていただいて、感謝ばかりです。
私自身IT素人でGitHubは初めて使いますのでコメントくらいしかできませんが、オープンデータのサイトは非公式ながらずっと気になっていて、もっと良い連携ができればいいのにと思っており、HP改修（といっても見栄え整理ですが）の担当になったので直接コメントさせていただいちゃいました。

私からもいろいろ相談したいですし、皆様からも「こんなことできるよ」とぜひぜひアドバイスいただければ嬉しいです。
何よりも県民の皆さん、全世界の皆さんにより良い情報発信をして、一刻も早くコロナの収束・終息を実現したいと思いますので、これからもお力添えをよろしくお願いします。

ちなみに、ツイッター等もチームで担当しています。
https://twitter.com/Nagano_Corona

**Comment by wataruoguchi** [comment]
新しいデータフォーマットの自動取り込みの変更を実施しました。今後本件は以下のissueで管理することとし、クローズします。
https://github.com/wataruoguchi/covid19_nagano_csv_to_json/issues/4
