### ISSUE TITLE
チャートカラーの設定を追従する

### ISSUE THREAD

**Issue by kikd** [Stop-COVID19-Nagano/covid19#123]
## 改善詳細 / Details of Improvement
- 対策サイトで使用しているチャートカラーを東京都の者に追従する。
https://github.com/tokyo-metropolitan-gov/covid19/issues/2364 がクローズしているので対応可能だろうと判断しました。

### なぜ追従するか？
東京都のサイトで使用しているチャートカラーは色覚多様性について考慮されたデザインになっています。
いろいろな方の利用を想定した場合、この設定を追従したほうがより使いやすいサイトになると考えています。

### 懸念事項
- 4色以上のチャートに対応できていない。
- 長野県のブランドカラーがある場合、そちらに合わせたほうがよさそう

## 期待する見せ方・挙動 / Expected behavior
- 東京都と同じ設定でチャートが表示される

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by ShinoharaTa** [comment]
時間見つけてサッとやっておきます

**Comment by kikd** [comment]
助かります！
