### ISSUE TITLE
検査陽性者の状況 カードが表示されない

### ISSUE THREAD

**Issue by kikd** [Stop-COVID19-Nagano/covid19#124]
## 起こっている問題 / The Problem
- 検査陽性者の状況カードが表示されていません。

## スクリーンショット / Screenshot

* ブラウザの表示
![image](https://user-images.githubusercontent.com/5682821/80339567-e6b1b080-8899-11ea-8981-95547da7474b.png)

* 開発者ツールのコンソール表示
![image](https://user-images.githubusercontent.com/5682821/80339639-13fe5e80-889a-11ea-9e88-882df3629a60.png)

## 期待する見せ方・挙動 / Expected Behavior
- 検査陽性者の状況 カードが表示される

## 起こっている問題の再現手段 / Steps to Reproduce
1.https://nagano.stopcovid19.jp/ を開く

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kikd** [comment]
アプリケーション側のデータ参照方法を見直す必要がありそうです


-----
この辺りだと推測してます
https://github.com/Stop-COVID19-Nagano/covid19/blob/bac3c2b174f959285c9a9c1bb0477a98881984ee/utils/formatConfirmedCases.ts#L42-L45

**Comment by kikd** [comment]
スクリプト側の状況見て判断します
https://github.com/wataruoguchi/covid19_nagano_csv_to_json/issues/4

**Comment by wataruoguchi** [comment]
FBみました。これはスクリプト側で吸収した方が良さそうですね。今夜対応します。

**Comment by kikd** [comment]
お願いします！

**Comment by wataruoguchi** [comment]
修正しました！こちらでも、発見報告ありがとうございました 🙏
