### ISSUE TITLE
「検査陽性者の状況」の退院と死亡がの数値が逆

### ISSUE THREAD

**Issue by tsuka39** [Stop-COVID19-Nagano/covid19#134]
## 起こっている問題 / The Problem
- 「検査陽性者の状況」の退院人数が0人、死亡が16人と表示されている。
- 退院と死亡の値が逆になっている

## スクリーンショット / Screenshot
![県内の最新感染動向___長野県_非公式_新型コロナウイルス感染症対策サイト](https://user-images.githubusercontent.com/23370404/80451601-38703e80-895f-11ea-8912-8368e0918d05.png)

## 期待する見せ方・挙動 / Expected Behavior
- 退院人数が16人、死亡が0人で表示される

## 起こっている問題の再現手段 / Steps to Reproduce
1. 　https://nagano.stopcovid19.jp/　の「検査陽性者の状況」のカードを確認

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by tsuka39** [comment]
data.jsonは大丈夫そう？
https://github.com/wataruoguchi/covid19_nagano_csv_to_json/tree/master/src/.json


![covid19_nagano_csv_to_json_data_json_at_master_·_wataruoguchi_covid19_nagano_csv_to_json](https://user-images.githubusercontent.com/23370404/80451765-9d2b9900-895f-11ea-8f80-2350223e7093.png)

**Comment by kikd** [comment]
修正しますー
