### ISSUE TITLE
更新日付とデータ内容に齟齬がある

### ISSUE THREAD

**Issue by wataruoguchi** [Stop-COVID19-Nagano/covid19#140]
## 起こっている問題 / The Problem
- "4/27の累計"　と　"2020/04/25 9:00 更新" のように、日付があっていない。

## スクリーンショット / Screenshot
<img width="571" alt="Screen Shot 2020-04-28 at 11 11 12 PM" src="https://user-images.githubusercontent.com/8963743/80565554-a0e20e80-89a5-11ea-9c04-ad61d08a5c53.png">
<img width="567" alt="Screen Shot 2020-04-28 at 11 10 11 PM" src="https://user-images.githubusercontent.com/8963743/80565558-a2abd200-89a5-11ea-9121-f39c93efc95a.png">
<img width="571" alt="Screen Shot 2020-04-28 at 11 09 34 PM" src="https://user-images.githubusercontent.com/8963743/80565559-a3446880-89a5-11ea-9551-5f88e9e94385.png">
<img width="572" alt="Screen Shot 2020-04-28 at 11 10 45 PM" src="https://user-images.githubusercontent.com/8963743/80565561-a3dcff00-89a5-11ea-8e4c-5e37651f9289.png">

## 期待する見せ方・挙動 / Expected Behavior
- `yyyy/mm/dd 9:00更新` は `m/ddの[合計|累計]` の一日後、だった気がします。データが悪いのかアプリが違うところをみているのかは未確認です。

**Comment by ShinoharaTa** [comment]
以前にもTokyoのサイトでここの表記がちがうことは指摘として上がっていたと思います。
更新日自体は、データ取得の部分なので、json内部の最終取得日時をベースとしていいのかなと思っております。

**Comment by kikd** [comment]
日付の齟齬は、アプリ側で違うところを参照していることが原因ぽいです。
`yyyy/mm/dd 9:00`は、data.jsonのpatients.date、`m/ddの[合計|累計]`はpatients_summary.data[]の最後の要素の'日付'からとってきています。

あと、データで気になったのは検査陽性者が0の日が続いていると次の日付が更新されていない点です。
* inspections.date  
* patients.date
* discharges_summary.date

**Comment by wataruoguchi** [comment]
@kikd デバッグありがとうございます！

> 検査陽性者が0の日が続いていると次の日付が更新されていない点です。

これ、心当たりあります。データ側にissueきりますね！

**Comment by wataruoguchi** [comment]
スクリプト側を修正しました。次のデータ更新時（ゴールデンウイーク明け？？）に確認できると思います。

**Comment by kikd** [comment]
スクリプトの修正ありがとうございます。
県のオープンデータですが、GW中も更新されているようです。(ありがたい…！)
スクリプト側にissue起こしたので確認お願いします

**Comment by wataruoguchi** [comment]
@kikd 新しい方のissueに対応しました。ページを確認して、昨日のデータが入っていることも確認しています。忙しいと思いますが、確認していただけますか？

**Comment by kikd** [comment]
@wataruoguchi 
スクリプト修正いただいてありがとうございます！
データも新しいものが反映されているのを確認できました！！
