### ISSUE TITLE
重症者数の取得について

### ISSUE THREAD

**Issue by tsuka39** [Stop-COVID19-Nagano/covid19#141]
@wataruoguchi 
200000_nagano_covid19_patients.csvの「患者_状態」に"重症"の表記はプライバシーにあたるとのことで、「患者_状態」には記載しないことになったそうです。
なので、現在画像で掲載しているデータを日ごとにまとめたデータを提供を検討してくださいました。
重症者数はここでしか取得できないので、、、摂り込むファイルが１つ増えてしまうのですが、こちらで進めていただこうと思いますが、いかがでしょうか。
[200000_nagano_covid19_patients_summary.xlsx](https://github.com/Stop-COVID19-Nagano/covid19/files/4552098/200000_nagano_covid19_patients_summary.xlsx)

**Comment by wataruoguchi** [comment]
@tsuka39

個人的には個人を特定できないのでプライバシーも何も、という感じで理解に苦しみます。それを言ったら性別や職業こそプライバ、、ゴホンゴホン

それでも、もしそういうことでしたら、specシートになるべく沿えるといいかな、と思って、今見ています。[https://www.code4japan.org/activity/stopcovid19](https://www.code4japan.org/activity/stopcovid19)

頂いたサンプルですが、`test_count` とやや重複するデータがありますね。累計値は`test_count`で計算すれば算出は容易です。県職員の仕事を増やすこともないかな、と。また、二重管理はよくないです。
そのため、以下の項目は `parients_summary` には含めない方がいいですね。

- 検査実施_累計
- 陰性確認_累計
- 陽性確認_累計

日毎の `parients.患者_状態` ("入院中" "重症" "退院等") を表すのがゴールだと思うので、
`parients.患者_状態`の選択肢である "無症状, 軽症, 中等症, 重症, 死亡" の当日合計、及び "入院中"の当日合計をまとめて頂くといいかもしれませんね。

こんな感じでどうでしょう？？死亡とか出せなければ、人数欄は空欄可にしておけばいいと思います。

- 年月日
- 全国地方公共団体コード
- 都道府県名
- 市区町村名
- 無症状_人数
- 軽症_人数
- 中等症_人数
- 重症_人数
- 死亡_人数

**Comment by tsuka39** [comment]
@wataruoguchi 
ありがとうございます！
画像に掲載している値をそのままだしているから、もしかしたら作業的に楽なのかな？ともおもったけど、でも、重複するデータをわざわざ出していただかなくてもよいですね。
今は軽症と中症は公開しないそうなので、

年月日
全国地方公共団体コード
都道府県名
市区町村名
無症状_人数
重症_人数
死亡_人数

こんな感じ？
無症状は画像に出してないし、今のところ表示する場所がないので、なくても良いかもしれない、、、

**Comment by wataruoguchi** [comment]
軽症と中症も入れておいたら、他の自治体にも使ってもらえるかな、と思ってます。長野は空欄でいいので。
これができたらCode for Japanの方にも連携しようかなーと

**Comment by wataruoguchi** [comment]
@tsuka39  `入院中_人数` もお願いします！

**Comment by wataruoguchi** [comment]
この順ですね。

- 年月日
- 全国地方公共団体コード
- 都道府県名
- 市区町村名
- 無症状_人数
- 軽症_人数
- 中等症_人数
- 重症_人数
- 死亡_人数
- 入院中_人数

**Comment by tsuka39** [comment]
@wataruoguchi 
県の方へ提案してきました！
回答きたらシェアしますね。

プライバシーの判断は自治体それぞれですねー。
陽性者属性では状態も居住地も公開していない地域もあれば、千葉県はPDFや市の公開情報まで見れば結構細かいこと掲載している感じ。

陽性者属性で状態（特に、退院や死亡）のステータスを持たない地域もあり、さらっと調べたら山口県や福井県はその日の人数を別ファイルで公開する方法でした。
（私も重体や死亡のケースを今は考えたくなくて、つい避けがちに、、、）

長崎県はAPIで提供されていたり、地域の対応がさまざまで興味深い。

**Comment by wataruoguchi** [comment]
連絡ありがとうございます。よろしくお願いします！

**Comment by tsuka39** [comment]
@wataruoguchi
おまたせしましたー
返事が来なかったので、県の担当の方に連絡してみました。
で、返事がきて、、、今回は対応しないとのことでした。

県のページ内容の見直しで掲載内容の追加があり、更新作業の負担が増えている状況だそうです。
現状は、感染者数の発生も緩やかになり、退院者数が入院者数を上回っている状況なので、CSVでの掲載データについては、現状のままとさせていただければとのことでした。
今後、状況の大きな変化してきたら、再度検討するかもしれないと。

むーー、残念。。

更新作業の負担が増えているというのが、ちょっと心配ですね。
こちらのサイトに負荷分散できれば良いのですが、、、

**Comment by wataruoguchi** [comment]
@tsuka39 ご確認頂きありがとうございました！オープンデータ、オープンソースが浸透するにはまだまだ時間がかかりそうですね😞
