### ISSUE TITLE
「検査陽性者の状況」陽性者数が誤っている

### ISSUE THREAD

**Issue by kikd** [Stop-COVID19-Nagano/covid19#144]
## 起こっている問題 / The Problem
- 「検査陽性者の状況」陽性者数の数値が72人になっています。
  (5/8時点の正しい数値は73人)
陽性患者数の累計値、陽性患者の属性 は正しい数値になっています。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/5682821/81358688-2dad6a80-9112-11ea-9cda-d3631d5c8d22.png)

## 期待する見せ方・挙動 / Expected Behavior
- 「検査陽性者の状況」陽性者数が正しい数値になっている

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kikd** [comment]
検査陽性者の状況はdata.jsonのmain_summaryを参照しているので、data側の修正で解決するかもしれません。

**Comment by kikd** [comment]
it may have fixed
![image](https://user-images.githubusercontent.com/5682821/81371560-25b1f280-9133-11ea-8ca5-9b11ec2042a0.png)

**Comment by wataruoguchi** [comment]
@kikd 連絡するの遅くなりました！
こちら、スクリプトのバグでした。発見＆報告、ありがとうございました 🙏
