### ISSUE TITLE
カードを指定してシェアした場合のOGPが東京都のままになっている

### ISSUE THREAD

**Issue by ShinoharaTa** [Stop-COVID19-Nagano/covid19#145]
## 起こっている問題 / The Problem
各カード右下にあるシェアリンクをクリックし、それをTwitterなりでシェアするとOGP画像の静的生成が行われる。
この画像の対象及び、文字列が東京都となっており、長野県になっていない。

## スクリーンショット / Screenshot
↓シェア画面
![image](https://user-images.githubusercontent.com/23314412/81428192-e5845b80-9196-11ea-8ff0-da305c31280d.png)

↓Twitterでシェアされたときの表示内容
![image](https://user-images.githubusercontent.com/23314412/81427992-90484a00-9196-11ea-8545-769b3e5fcc2b.png)

## 期待する見せ方・挙動 / Expected Behavior
- 最終的な要望：長野県に対応したものにする
- 一次対応：各カードのシェアボタンを無効にする。

## 起こっている問題の再現手段 / Steps to Reproduce
1. トップページより、各カードの右下ボタンを押す
2. シェア画面が表示されるので、そのままTwitterまたはFacebook等でシェアをする

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kikd** [comment]
今夜見てみますー
