### ISSUE TITLE
長野県新型コロナウイルス感染症対策サイトが２つあるので混乱を避けるために１つにまとめてください

### ISSUE THREAD

**Issue by Neko7sora** [Stop-COVID19-Nagano/covid19#182]
## 改善詳細 / Details of Improvement
- 長野県新型コロナウイルス感染症対策サイトが２つあるので混乱を避けるために１つにまとめてください
https://github.com/Stop-COVID19-Nagano/covid19 @Stop-COVID19-Nagano
https://github.com/kanai3id/covid19 @kanai3id

**Comment by wataruoguchi** [comment]
@Neko7sora こんにちは！お問い合わせありがとうございます。二つ存在していることは認知しておりませんでした。@kanai3id のページはグラフがリッチですね！すばらしい！

まず、こちらの依頼の文脈を教えていただけますでしょうか？個人的には県民の方達にわかりやすく情報をお伝えするためのOSSプロジェクトですので、複数あっても支障はないと考えていますが、どなたが "混乱" を感じていますか？

そもそも県庁が以下のようなサイトを公表しているので、いずれかのサイトが混乱を生じているのであれば両OSSをクローズすることが正しい、という結論も可能性として考えられますか？

https://www.pref.nagano.lg.jp/hoken-shippei/kenko/kenko/kansensho/joho/corona-doko.html

**Comment by Neko7sora** [comment]
> 個人的には県民の方達にわかりやすく情報をお伝えするためのOSSプロジェクトですので、複数あっても支障はないと考えていますが、どなたが "混乱" を感じていますか？

現状、他都道府県のサイトによって情報の維持がされていない（自動的にグラフの更新されていない、2020年の情報のままになっているなど）状態で放置されているリポリジリがあり、いろいろと課題があります。

統一化の動きについては、

1. 県ごとにまとめることで管理がしやすくなる。
2. 2つのサイトの情報が違うと、混乱が起きてしまう。
3. 2つのサイトが違うリポリジリ上にあり、両方に問題点が見つかった場合に、Issues&Pull requestsしなければならない。
というのがあります。

他都道府県でも複数サイトあるところがあり、この都道府県ごとの統一化の動きを進めています。
https://github.com/orgs/stopcovid19-japan/projects/1

----

「混乱」というのは、両サイトともデザインが同じ状態が原因で起こる可能性があります。
1. 県民の人々の信頼して両方とも利用している時に2つのサイトの情報が違う状態が起こった場合
2. 両サイト同じ更新時刻であるという先入観によって"最終更新"を見ないでスクロールして情報が違っていた場合の混乱
もし、片方のサイトが緊急事態宣言が出されている説明があり、もう片方がその説明がなかった場合のとき、片方のサイトのみを見ている人の情報の格差が発生してしまい、緊急事態宣言を知らずに外出してしまい揉め事になってしまう可能性があります。両サイトの情報が違うことがのちに大事になってしまう可能性があります。

----

**Comment by Neko7sora** [comment]
> そもそも県庁が以下のようなサイトを公表しているので、いずれかのサイトが混乱を生じているのであれば両OSSをクローズすることが正しい、という結論も可能性として考えられますか？

OSSの方が
1. 正確な情報を届けるため、様々な情報やデータをグラフや表で分かりやすく掲載されている
2. ソースコードの公開により、世界中からの改善提案を受け付けることができるメリットがある

![image](https://user-images.githubusercontent.com/75793267/110428109-236e4b00-80ec-11eb-90fc-94e717f90823.png)

県庁が公表しているものだと、人によって
1. グラフが細かすぎてわかりすらい点
2. 色の配色が色覚異常者にとって見づらい点

![image](https://user-images.githubusercontent.com/75793267/110428114-249f7800-80ec-11eb-902a-9c9c8fdc643a.png)

自分は、OSSの方が見やすいと思います。

**Comment by wataruoguchi** [comment]
@Neko7sora お返事いただきありがとうございます。あなたが懸念されていることをデータで示すことは可能でしょうか？「一つにまとめる」ということにはコストや時間がかかりますが、その作業に値するデータがいただけると、もしかしたらどなたか作業できるかもしれません。
また、本プロジェクト自体はOSSですので、他方のプロジェクトオーナーと交渉の上であなたからPR頂ければ私の方で喜んでコードを確認させていただきます。

また、引用頂いたこちらのorganization https://github.com/stopcovid19-japan に存在する https://github.com/stopcovid19-japan/stopcovid19.page.link も今までに多くの方が似たようなものを作られているかと思いますが、こちらも重複プロジェクトですので同じ言説ですと同じ理由で混乱を招きませんか？参考までに　https://stopcovid19.code4japan.org/tables/area-tables

**Comment by kikd** [comment]
ご意見いただきありがとうございます。

内容については @wataruoguchi さんと同意見です。

わたくしとしては以下の点についてお伺いいたします。 
* 対策サイトが複数存在している現状において、「"誰"が、"どの程度"混乱しておられるのか」という明確なデータはお持ちでしょうか。
* > 他都道府県でも複数サイトあるところがあり、この都道府県ごとの統一化の動きを進めています。

  とのことですが、こちらはどなたが(またはどのグループ)が主導となり進めておられるのでしょうか。
  統一化の動きが決定したまでのログなどがありましたら、合わせてお教えいただけますでしょうか。
* 市の単位で対策サイトを運用されている自治体もございます。 この場合は”混乱を招く”ことにはならないのでしょうか。

**Comment by kanai3id** [comment]
@wataruoguchi さん、こんにちは。
後出しで長野県版をリリースしてしまった @kanai3id です。
職業柄がちがちのルールの中でIT業界に携わっていることから、当時はコロナ渦で長野県の為に、ひとりで気楽に（この気持が強い）、知らないテクノロジーを触ってみたかったという安易な気持ちで立ち上げてしまいました。わたしさえ立ち上げなければ問題にならなかったのにと...すみません。

さて、茨城県版でも同じことが議論されていました。
https://github.com/a01sa01to/covid19-ibaraki/issues/289#issuecomment-792688940

こちらにコメントがありましたが、依頼人は"Code for Japan"の"covid19プロジェクト"の関係の方のようです。

わたしのサイトは長野県非公式ですが、いちおう長野県企画振興部情報政策課の方にオープンデータ利用についての連絡と了承と"Code for Japan"の"covid19プロジェクト"へはgitで連絡とリンクも貼られているので問題ないと思っていました。

本ISSUEと茨城版のISSUEを読みましたが、どうやら"Code for Japan"の"covid19プロジェクト"の本OSSの利用を県ごとに1つにせよという理解です。

"Code for Japan"の"covid19プロジェクト"の担当の方から閉じろと依頼されれば閉じますが、茨城版の @BenataY さんのコメントにもありましたが同じ思いです。

> 私個人としては、あまりサイトの保持に固執はない反面、ここまで運用してきた以上、コロナがキチンと落ち着くまでやり抜きたいなと言う思いもあります。

難しいことはあまり議論したくはありませんが、オープンデータの利用についてはどうでしょうか？わたしが認識しているだけでも、本OSSを利用せずに長野県の情報を発信している方はこちらの２つあります。
https://nagano-graph.com/   → こちらもしかすると covid19 projectのOSSかもしれません
https://twitter.com/gyakutenamerica/status/1369259985780142081
本OSSを利用していなケースの場合はこちらをどのように考えるのか？こちらは混乱するのかしないのか？

今後本件についての交通整理が行われていく？のであればこちらで引き続き確認とコメントなどはさせて頂きます。

以上、引き続きよろしくお願い致します。

追記：統合しろと依頼された場合、面倒なので断ります。オープンデータをaggregateするコードはあまりにも汚すぎてgitへも載せられませんｗ治すのも面倒なのでサイトごと閉じます。

**Comment by wataruoguchi** [comment]
@kanai3id こんにちは！サイト開発、運営、お疲れ様です。私は各々が今までにかけてきた時間や労力は評価されるべきですし、非中央集権的な組織だからこそ類似サービスが複数立ち上がることは十分に予想されており、そこに問題を感じていません。

私は同組織のcovid19プロジェクトを一年ほど観測しております。これまでにいくつもの全国版まとめサイトが作られてきましたが、いずれのプロジェクトにおいても一つの自治体に複数のサイトが存在することに非を唱えられた事はないと記憶しています。
また、本件が課題として挙げられたことも、議論を見たことも記憶にありません。（起票者ご本人の発言は確認しています。）

<img width="430" alt="Screen Shot 2021-03-09 at 9 07 32 PM" src="https://user-images.githubusercontent.com/8963743/110579346-790e1c00-811b-11eb-9a84-7e1420dc1213.png">

> 本家covid19内の依頼ではなく、本家covid19を開発した"Code for Japan"という団体の"covid19プロジェクト"に参加している人の依頼です。

むしろ上記の発言の曖昧さや理由の不明瞭さから、失礼かもしれませんが信憑性を感じることができず、これ以上の議論に値するか疑念を感じております。

@kanai3id の発言からお互い現状維持のままが好ましいと受け取りますので、問題があればPR作成を是とし、本件クローズします。
