### ISSUE TITLE
オープンデータのURL変更

### ISSUE THREAD

**Issue by tsuka39** [Stop-COVID19-Nagano/covid19#186]
## 改善詳細 / Details of Improvement
- オープンデータのURLに変更があったため、オープンデータのリンクを新しいURLにする
- 変更前：https://www.pref.nagano.lg.jp/joho/kensei/tokei/johoka/opendata/
- 変更後：https://www.pref.nagano.lg.jp/dx-promo/kensei/tokei/johoka/opendata/index.html

## 期待する見せ方・挙動 / Expected behavior
- エラーにならずに長野県オープンデータサイトが表示される

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kikd** [comment]
issue作成ありがとうございます！
こちら変更しておきますー
