### ISSUE TITLE
サイト内情報について

### ISSUE THREAD

**Issue by ghost** [Stop-COVID19-Nagano/covid19#193]
サイト内「お子様をお持ちの皆様へ」内の相談の目安「37.5℃以上の発熱が４日以上」といったもの等が、厚生労働省のほうで昨年修正されております。確認とご修正願えませんでしょうか。ご検討宜しくお願い致します。※「コロナ 相談 目安 変更 37.5」で検索

**Comment by kikd** [comment]
ご指摘いただきありがとうございます。
サイト作成時の情報のまま更新ができておらず、申し訳ございません。

[厚労省の記載](https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kenkou_iryou/dengue_fever_qa_00001.html#Q1-8)に合わせて修正いたします。

**Comment by ghost** [comment]
若干細かい事にも関わらず、ご対応ありがとうございます。ご修正宜しくお願い致します。
