### ISSUE TITLE
自動取得したcsvからpatients_summaryを作りたい

### ISSUE THREAD

**Issue by tsuka39** [Stop-COVID19-Nagano/covid19#20]
## 改善詳細 / Details of Improvement
- 自動取得しているcsvからkensa.jsonが作成され、data.jsonの一部を作成している
- その時に現状、手作業で更新しているpatients_summaryも生成してほしい

## 期待する見せ方・挙動 / Expected behavior
- kensa.jsonとpatients_summaryのマッピングはスプレッドシートに追記しました
https://docs.google.com/spreadsheets/d/1PWwV2bn9N9C2Cfox9-KdXDryIkRPh6LEpbXVZsAfwwM/edit#gid=0

**Comment by wataruoguchi** [comment]
`patients_summary` 追加しました。現時点以降に自動生成される`data.json`についてくるはずです。

https://github.com/wataruoguchi/covid19_nagano_csv_to_json/commit/edfed1a93ddb0941d75b75140afc6de71bea2772
