### ISSUE TITLE
vue-i18n build warnings

### ISSUE THREAD

**Issue by wataruoguchi** [Stop-COVID19-Nagano/covid19#24]
## 起こっている問題 / The Problem
`vue-i18n` build warnings. 多言語をサポートしていなければ重要ではありません。

## スクリーンショット / Screenshot

<img width="743" alt="Screen Shot 2020-03-26 at 8 03 02 PM" src="https://user-images.githubusercontent.com/8963743/77717155-f25d3f00-6f9c-11ea-986f-63a5b30f6265.png">

## 期待する見せ方・挙動 / Expected Behavior
- xxxx(できるだけ簡潔に/as concise as possible)

warningsが発生しないこと。文字が翻訳されていること。

## 起こっている問題の再現手段 / Steps to Reproduce
1. Run `$npm run dev`

## 動作環境・ブラウザ / Environment
- macOS

**Comment by uryoya** [comment]
翻訳できていない言語に関しては一旦削除して、エラーが出ないようにしても問題ないのではないでしょうか？

**Comment by wataruoguchi** [comment]
@uryoya いいと思います！PRお願いします 🙏

**Comment by uryoya** [comment]
@wataruoguchi 承知しました！開発始めます

**Comment by uryoya** [comment]
エラーについてですが、「翻訳の足りない言語があるためエラーになっていた」わけではなく「翻訳テンプレート( `$t(<message>)` )内で使われている文字列と `*.i18n.json` ファイルで定義されている文字列が一致していない」ことが原因でした。以下のような箇所です。
https://github.com/hisayan/covid19/blob/212ff0fb85a68d41b647e4b568bfdc37191cc32d/pages/index.vue#L78
https://github.com/hisayan/covid19/blob/212ff0fb85a68d41b647e4b568bfdc37191cc32d/pages/index.i18n.json#L3
よって `*.vue` 内の文章（文字列）については翻訳を修正する対応をします。


また「最新のお知らせ」のリンクの文字列も同様のエラーが出ていますが、本家サイトが `$t(...)` を削除しているので同様の対応をします。
https://github.com/tokyo-metropolitan-gov/covid19/commit/b3774328adcbff03114c9bdad91e47ea80689334#diff-ee17d945364eb4e87ed72ea318008e7a
