### ISSUE TITLE
"最新のお知らせ" が大きくなり始めているのでscrollableにしたらいいかも

### ISSUE THREAD

**Issue by wataruoguchi** [Stop-COVID19-Nagano/covid19#25]
## 改善詳細 / Details of Improvement
- 東京都は最新の数件だけを表示していますが、長野県は全部表示させています。私はそれは良いことだと考えています。ただ、"最新のお知らせ" がグラフを下に押し始めているので、一覧の高さをある程度固定にしてscrollableにしたらいいかもしれません。

CSSの `overflow` 使ったら簡単にできそうです。優先度低め。

**Comment by 853ro** [comment]
はじめまして！
初心者ですが、何かしら参加させていただきたく、こちらのissueをやってみました。
プルリクエストしておりますので、よろしくお願いします。
