### ISSUE TITLE
陽性患者の属性に表示されている日付が一致していない

### ISSUE THREAD

**Issue by kikd** [Stop-COVID19-Nagano/covid19#29]
## 起こっている問題 / The Problem
- 右上の累計で表示している日付と更新日の日付が一致していない。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/5682821/77726697-dbb9f500-703b-11ea-98cc-e7be27192767.png)

## 期待する見せ方・挙動 / Expected Behavior
- 累計の表示日時と更新日の日付が一致している

## 動作環境・ブラウザ / Environment
- Windows

**Comment by wataruoguchi** [comment]
#28 の改善でデータソースを一貫させれば解消できるかもしれません。

**Comment by kikd** [comment]
こちらのissue、今確認したら直っているので一度closeします。
![image](https://user-images.githubusercontent.com/5682821/78422644-b7919000-769b-11ea-8d1a-75dae33cc793.png)

**Comment by wataruoguchi** [comment]
@kikd 放置してました。確認&closeありがとうございます 🙏
