### ISSUE TITLE
「検査陽性者の状況」のデータ整理

### ISSUE THREAD

**Issue by tsuka39** [Stop-COVID19-Nagano/covid19#3]
この辺確認する。
・どこからデータを収集するか
・どこファイルを更新するか

**Comment by tsuka39** [comment]
soudan0317.csv（日付でファイル名が変わる）があるけど、
「すべて陰性」「うち1件陽性」のような文字列なので、今は目視確認が必要。


北海道版のドキュメントを流用してまとめました。
現状を共有。
https://docs.google.com/spreadsheets/d/1IZw-M2FJ06n8Q6pzJxQGD32ksiBCa9E4T7snlrMMLCw/edit?usp=sharing

**Comment by wataruoguchi** [comment]
@tsuka39 CSVをfetchしてJSONに変換するスクリプトを作りました。ただ今READMEを書いているところです。pushしたらまたお知らせします。

**Comment by wataruoguchi** [comment]
@tsuka39 @hisayan お納めください。
https://github.com/wataruoguchi/nagano-covid19-data

週末にでも CLI -> GitHub Action で毎日更新できるようにしようと思っています。

**Comment by tsuka39** [comment]
@wataruoguchi 
素晴らしい！！
ありがとうございます！
引き続き、よろしくお願いします、

csvでこんな風にして欲しいって要望あったら、県庁に伝えるので教えて欲しいです。
通るかどうかは微妙だし、作っていただいてるのがあるので変えない方が良いと思いますが、県とコミュニケーションを続けていきたいのです。

**Comment by wataruoguchi** [comment]
@tsuka39 確認ありがとうございます。jsonフォルダに本日分のデータを入れてあります。

県庁にデータ修正の依頼をしようとも思いましたが、きっと彼らはExcelで作ってると思います。エンコードとは？フォーマットとは？のレベルからデータをオープンにしてくれているので、技術でどうにかできる部分はプライオリティは低くて良いです。
それよりも、「公開していただいているオープンデータでこれ作りました！」「オープンデータでこんなことができます！もっとオープンにしてください！」というところを強調した方が"県とコミュニケーション"をとるのに適していると考えています。

**Comment by tsuka39** [comment]
@wataruoguchi 
なるほど！
ありがとうございますー
今、出先なので帰ったら見ますね！

長野県にはそんな感じで連絡してみます！

**Comment by wataruoguchi** [comment]
@tsuka39 ご理解ありがとうございます。県に連絡できるようでしたらフォーマット変えないでくださいってことだけ伝えて頂ければありがたいです🙏出身地に貢献できたら幸いです 👍

**Comment by tsuka39** [comment]
@wataruoguchi 
お返事、遅くなってすみません。
作っていただいたの、見させていただきました！
結構なコード量なのに、早いですね、、すごい。

せっかく自動化していただいたので、jsonをそのまま使えるようになると良いのかなと。
長野版は東京版のdata.jsonをそのまま流用しています。

表示処理をsoudan.jsonとkensa.jsonに合わせて修正する方法もあると思いますが、こちらの方が作業量大きいですよね・・・？

同じ構造で出力していただけるとそのまま利用できるので、取り急ぎ、kensa.jsonとdata.jsonのマッピングしてみます。
できたらまたご連絡します。

**Comment by tsuka39** [comment]
@wataruoguchi 
まとめてみました！
そして、相談させてください。

ふと思ったのですが、、、
kensa.jsonやsoudan.jsonからdata.jsonに利用できるjsonを出力する処理を作成した方が良いですか？
もし、そうでしたら別のissueにした方が良いのかなと思いまして。

kensa.jsonからdata.jsonへ
https://docs.google.com/spreadsheets/d/1PWwV2bn9N9C2Cfox9-KdXDryIkRPh6LEpbXVZsAfwwM/edit?usp=sharing

soudan.jsonからdata.jsonへ
https://docs.google.com/spreadsheets/d/1SzMw0_Kg4MJJmgafq0NUeYEKdxAiyvPT_wWxWl-zrNw/edit?usp=sharing

**Comment by wataruoguchi** [comment]
> kensa.jsonやsoudan.jsonからdata.jsonに利用できるjsonを出力する処理を作成した方が良いですか？

@tsuka39 jsonを別のjsonにするコードを書くのはマッピングさえできてれば一瞬でできる簡単な作業です。マッピングを既にしてくださっているようなので必要があれば私ができますよ。
実はcovid19のレポジトリまだ見てないですが、他の自治体のフォークしたものをみる限り、data.jsonに準拠してなくてもグラフを表示させることはできるんじゃないかなーと思ってます。

とりあえず、今あるJSONで https://stop-covid19-nagano.netlify.com/ 更新して頂けるとありがたいです。

**Comment by tsuka39** [comment]
@wataruoguchi 
data.jsonに準拠するってなると、手作業が発生するので、せっかく自動化が、、、ですね。
必ずしも準拠しなくちゃいけないではないし、kensa.jsonやsoudan.jsonを使って表示できると素敵かも。自動化。
issueをたてますー

**Comment by wataruoguchi** [comment]
@tsuka39 失礼しました。きっと意思疎通ができていませんでした。data.jsonに準拠するよう自動化できますよ。今から手を動かします

**Comment by tsuka39** [comment]
@wataruoguchi 
いえ、こちらこそ、理解が遅くてすみません。
自動化できるんですねー。素晴らしい。。
ありがとうございます！
対応、よろしくお願いします！！

**Comment by hisayan** [comment]
作っていただいたのを、よりスムースにするために、明日、時間とって、data.json の、外だし（てか、ただの参照に、都度のdeploy不要）にできないか、みてみますね。
北海道チームのが、参考になるというウワサも。

**Comment by wataruoguchi** [comment]
@tsuka39 私のスクリプトに頂いたマッピング情報を元にsoudanとkensaからdata.jsonを生成する機能を追加しました。以下のページ内のdata.jsonをご確認ください。

https://github.com/wataruoguchi/covid19_nagano_csv_to_json/tree/master/src/.json
これらのファイルは平日毎日更新される予定です。

@hisayan コメントありがとうございます。
アプリケーションの作り方次第ですが、

動的アプリの場合：
私のリポジトリ内のそれぞれのjsonファイルへリンクして頂ければ、都度のdeployは不要になるかと思います。

静的アプリの場合：
データ更新の度にデプロイが必要かと思います。自動デプロイをご検討しているようでしたら私のスクリプトのリポジトリの更新をsubscribeするといいかと思います。

**Comment by hisayan** [comment]
@wataruoguchi 動的にできないかな〜とおもっているのですが、そのときって、
header('Access-Control-Allow-Origin: hogehoge')
してもらわないと、動かない気がしています。
でもって、localhost でテストしたり、dev やら prod やら考えると、* にしてしまうほうが楽な気もしているのですが、そもそも github ちょくで、header 付加はできないですよね？

**Comment by hisayan** [comment]
このURLでJSON取得すると、そもそも * になっているようですね。
https://raw.githubusercontent.com/wataruoguchi/covid19_nagano_csv_to_json/master/src/.json/data.json

**Comment by wataruoguchi** [comment]
@tsuka39 @hisayan このissueはもうクローズしても良いかと。

**Comment by hisayan** [comment]
スマホで操作したら、変になってしまった。ごめんなさい。閉じてまたひらいてしまった。
