### ISSUE TITLE
"県内の最新動向"の最終更新日時が消える

### ISSUE THREAD

**Issue by kikd** [Stop-COVID19-Nagano/covid19#30]
## 起こっている問題 / The Problem
- 県内の最新動向の最終更新日時が一瞬表示されるが、すぐに消えてしまう

## スクリーンショット / Screenshot

![issue](https://user-images.githubusercontent.com/5682821/77727835-816e6380-703e-11ea-9d07-280a6e176260.gif)

## 期待する見せ方・挙動 / Expected Behavior
- 最終更新日時が表示されている

## 動作環境・ブラウザ / Environment
- Windows

**Comment by wataruoguchi** [comment]
#28 の改善でデータソースを一貫させれば解消できるかもしれません。

**Comment by kikd** [comment]
CSVからJSONに変換する際、"lastUpdate"をつけると解決するかもしれません。
https://github.com/hisayan/covid19/blob/development/data/data.json#L2074

(該当箇所はそこを参照しているようです。)

**Comment by wataruoguchi** [comment]
@kikd おお！すばらしい！CSV->JSON のマッピングから漏れていたのかもしれません。`lastUpdate` だけでなく `main_summary` も漏れてますね。明日は忙しいので明後日以降の変更になりそうです。調査して頂きありがとうございます 🙏

**Comment by wataruoguchi** [comment]
FYI @kikd  issue つくりました: https://github.com/wataruoguchi/covid19_nagano_csv_to_json/issues/1

**Comment by tsuka39** [comment]
@wataruoguchi 
CSV->JSON のマッピングでいうと、「patients」も含まれていません。
patientsとmain_summary はcsvで提供されていなくて、こちらのPDFの情報も必要になってくると思います。
陽性者数はcsvファイルから取得できるけど、退院情報はPDFで提供されています。
https://www.pref.nagano.lg.jp/hoken-shippei/kenko/kenko/kansensho/joho/documents/hasseizyokyo0329.pdf

こちらのPDFファイルをcsvで提供していただきたいと先週、長崎県の担当の方に連絡して、「確認して連絡します」とのことで、今は待ちの状態です。

**Comment by wataruoguchi** [comment]
本件、スクリプトをアップデートしました。4月1日データには反映されることでしょう。
https://github.com/wataruoguchi/covid19_nagano_csv_to_json/issues/1

`main_summary` は途中まで作りました。退院情報や他の情報のCSV, JSONなどでの公開をお待ちしております、とお伝えください。

**Comment by wataruoguchi** [comment]
@tsuka39 patients & main_summary を新しく提供されたcsvから生成するよう、自動スクリプトを更新しました。4月2日データからきっと使えるようになるかな、と。これらの項目が追加された新しいJSONができたら、またお知らせします。
