### ISSUE TITLE
自動生成された情報（news.json）で「最新のお知らせ」を表示したい

### ISSUE THREAD

**Issue by tsuka39** [Stop-COVID19-Nagano/covid19#33]
## 改善詳細 / Details of Improvement
- news.jsonを長野県のサイトから自動生成するスクリプトで作成された、news.jsonのデータを「最新のお知らせ」に表示されるようにしたい。
- https://github.com/wataruoguchi/covid19_nagano_scraper

## 期待する見せ方・挙動 / Expected behavior
- 手動でnews.jsonを更新しなくても最新の情報が「最新のお知らせ」に表示されるようになる。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by ShinoharaTa** [comment]
実現に向けて。

# 速報性があるが、開発規模が大きくなる

現時点でNuxtがuniversalでnetlifyに静的ホスティングされていると思われます。
こちらのデータを動的に取得する場合、NuxtではAxios仕様時にCORSエラーなどに悩まされます。
現時点で有効と思われる方法は、Mixhostが無料でVPSを建てられるため、ここで定期実行したjsonをCORS対策し公開→サイトからはAPIを叩くような感じで取得という方法が現実的かと思います。

# 開発コスト小、リアルタイム性は無いが、generateのときに更新される

generateするときに静的ホスティングは可能です。
Axiosで取得先にjsonファイルを指定すれば、generateコマンドが走ったときに取得し、マージなどのサイト更新のタイミングで更新することは可能です。

**Comment by wataruoguchi** [comment]
新しいデータが出たらGitHub webhookで通知が飛ぶはずなので、それをsubscribeして毎回ビルドしたら動的取得する必要はないと思ってます。その辺はこっちのissueで明日か明後日を目処にやろうと思ってます。
https://github.com/Stop-COVID19-Nagano/covid19/issues/28
