### ISSUE TITLE
masterにマージした修正が本番環境に反映されない

### ISSUE THREAD

**Issue by tsuka39** [Stop-COVID19-Nagano/covid19#40]
3/29 23:46にdevelopmentからmasterにマージした修正内容が、3/30 1:15時点で本番環境に反映されていません。

このPull Request（https://github.com/hisayan/covid19/pull/36）で反映された状態で本番環境が見れるようにしてほしい。

開発環境は正しく反映されています。

**Comment by hisayan** [comment]
netlify で fail していました。retry してもだめだったんだけど、netlify のキャッシュをクリアして retry deploy したら、進んだような気配です。
根本調査はできていませんが。反映されている感じありますか？

**Comment by tsuka39** [comment]
@hisayan 
ありがとうございます！！
反映されてた！！

**Comment by tsuka39** [comment]
その後のmasterへのマージもdeployされたので、このissueはCloseします。
