### ISSUE TITLE
「検査陽性者の状況」の表示

### ISSUE THREAD

**Issue by tsuka39** [Stop-COVID19-Nagano/covid19#5]
data.jsonの最後にあるmain_summaryに最新データをセットしました。
値はWebページから目視で取得するしかないです。

たぶん、「検査陽性者の状況」で使用しているカラムだと思う。
データの取得元がわかったので、表示できるよう対応お願いします。

※pushができてないので、最新データはここにおいてあります（3/19現在）
https://drive.google.com/drive/folders/1wae4Pwwqv7q03S7FTEZjsoZ5Aiy0nOfH?usp=sharing&fbclid=IwAR0MRranxpeOyuzzEDFFloPeEZJiY-RFXK4U4tU9KeAOk-v3jOThRn0SikU

**Comment by kikd** [comment]
こちら対応します
(PR出すのは明日の午前になりそうですが…)

**Comment by wataruoguchi** [comment]
FB group https://www.facebook.com/groups/155315052273089/ には参加リクエストを送りましたが未だ承認されていないのでこちらに書き込ませていただきます。

以下のissueでも書きましたがデータ取得スクリプトを書きました。これから手を加えていく予定です。一助になれば幸いです。
https://github.com/hisayan/covid19/issues/3

**Comment by tsuka39** [comment]
@kikd 
対応、ありがとうございます！！
よろしくお願いします！！

@wataruoguchi 
FBグループの管理権限を持っていないので承認処理ができなくてすみません、、
おそらくOguchiさんらしきFBアカウントに塚原からお友達申請させていただきました。
招待できれば参加できるはず、、、
