### ISSUE TITLE
お知らせの下に県公式の新型コロナウイルスに関する直リンクを設置したい

### ISSUE THREAD

**Issue by ShinoharaTa** [Stop-COVID19-Nagano/covid19#55]
お知らせ一覧の下に、長野県公式サイトの新型コロナウイルス関連のページヘの直リンクを設置し、アクセシビリティを高めるのはどうでしょうか。
また、同様に教育委員会からの発表に関しても直リンクを設置したい。

https://www.pref.nagano.lg.jp/hoken-shippei/kenko/kenko/kansensho/joho/corona-naganoken-taiou.html

https://www.pref.nagano.lg.jp/kyoiku/kyoiku/corona.html

**Comment by tsuka39** [comment]
良いですね！
「最新のお知らせ」エリアはスクロールするようになっていて、下だと隠れてしまいますね。。
左側の「県民の皆様へ」や「長野県公式ホームページ」の並びに入れるのも良いかなと思いました。

**Comment by ShinoharaTa** [comment]
入れる場所などについては後ほど、画像つきで案をここに掲載します

**Comment by ShinoharaTa** [comment]
先程確認したところ、長野県公式サイトが全部で5つのページに分割されていることを確認しました。
それ以外にも直リンが必要と思われるリンク一覧を書き出し、それをサイドメニューに掲載しようと思います。

https://www.pref.nagano.lg.jp/kenko/kenko/kansensho/index.html

![image](https://user-images.githubusercontent.com/23314412/78379109-d9900180-760c-11ea-943e-1e105bcdc453.png)

**Comment by ShinoharaTa** [comment]
下記の順番で掲載しようかなと思っております。

1. 長野県公式ホームページ（トップ）
1. 新型コロナウイルスについて（新型コロナウイルスに関するトップページ）
1. 新型コロナウイルスの基礎知識
1. 対策についてのお願い
1. 新型コロナウイルスに関しての相談窓口（相談窓口ページ）
1. 長野県の対応

文言など、修正ありましたらお願いします。
修正はこれから対応入ります。

**Comment by kikd** [comment]
「長野県公式ホームページ」を公式ホームページ一覧というページを作成し、
そこに各リンクを載せるのもアリかなと思います。


この方法だとサイドメニューの長さをおさえることができます。
その反面、公式ホームページへ行くためのユーザー操作が1ステップ増えてしまいます。。

**Comment by ShinoharaTa** [comment]
お知らせと同じ幅のカードを作ってトップページに掲載するのはいかがでしょうか。
それでしたら新規ページを建てる必要もなく、ユーザーステップ数も増えることがないため対応可能となります。

**Comment by kikd** [comment]
相談窓口のリンクがあるカードに足してみてもいいかも、と思いました。

**Comment by ShinoharaTa** [comment]
PC, スマートフォンでそれぞれこのような感じになります。

![image](https://user-images.githubusercontent.com/23314412/78752245-b1a6f200-79ae-11ea-84e7-0226df825e59.png)

![image](https://user-images.githubusercontent.com/23314412/78752218-a2c03f80-79ae-11ea-8aa8-a93caa91c21e.png)

実際にコード書いて見た感覚ですが、意外と項目数が多くなる傾向にありますね。もうちょっとスマートにまとめる方法があるのが理想ではありますが・・・

**Comment by ShinoharaTa** [comment]
先程おっしゃっていたように、長野県の公式サイト一覧を別ページにまとめたほうが理想的な気がしてきましたので、実装を見直します。

**Comment by ShinoharaTa** [comment]
先程確認しましたが、項目が目次にまとめられていたので、この目次に沿って設置を考えます。

![image](https://user-images.githubusercontent.com/23314412/78755240-c89c1300-79b3-11ea-821b-508f1282c044.png)

もしかして、各官公庁とかおすすめサイトとかを掲載するページを作り、そこに県公式のリンクとして記載する等の方法を検討します。

**Comment by ShinoharaTa** [comment]
項目は現時点では整理していませんが、このような感じで表示することを検討しています。

![image](https://user-images.githubusercontent.com/23314412/78817981-eb0f4a00-7a0e-11ea-9868-972cf5fa25a8.png)
※画像差し替えました(4/9 3:05

**Comment by kikd** [comment]
綺麗にまとめられていていいと思います！

**Comment by tsuka39** [comment]
見やすい！

**Comment by ShinoharaTa** [comment]
ありがとうございます。
もう少々コードを整理したらアップしようと思います。
