### ISSUE TITLE
Google Analytics関連の文章について

### ISSUE THREAD

**Issue by MaySoMusician** [Stop-COVID19-Nagano/covid19#58]
## 改善詳細 / Details of Improvement
- 現行の `about.vue` ではGoogle Analyticsについて
    > 個人を特定する情報を**含まずに**Webサイトの利用データ（アクセス状況、トラフィック、閲覧環境など）を収集して

  となっているが、tokyo-metropolitan-gov/covid19#1471 で[指摘があったように](https://github.com/tokyo-metropolitan-gov/covid19/issues/1471#issuecomment-599255049)Google Analyticsが収集するデータは個人を特定できるものであるので、文章を変更する必要がある

## 期待する見せ方・挙動 / Expected behavior
- https://github.com/tokyo-metropolitan-gov/covid19/pull/2177/files#diff-9aa1b4d61222a570d303632c7712e59b や https://github.com/tokyo-metropolitan-gov/covid19/issues/1471#issuecomment-608164321 のような文章に変更する
- もしくはGoogle Analyticsの使用を停止する

**Comment by kikd** [comment]
東京都からの展開ありがとうございます！

@hisayan 
google analyticsって現状運用している or 運用の予定ありますでしょうか？

**Comment by hisayan** [comment]
タグは最初に埋め込んでます。google アカウントおしえていただいたら、権限シェアします〜

**Comment by ShinoharaTa** [comment]
こちらの対応も同時に進めようかと思いましたが、今のところja.jsonのみなのですね・・・。
本家がCloseしたらこちらも追って対応します。

GAなり、Netlifyの閲覧権限は別でissues建てて、ピン留めしておくのいかがでしょう。

**Comment by ShinoharaTa** [comment]
すでにコードは対応済み。
#103 とコンフリクト起きそうなので、devにマージされ次第、こちらでマージしてからPull request出す予定
