### ISSUE TITLE
「相談件数」の表示

### ISSUE THREAD

**Issue by tsuka39** [Stop-COVID19-Nagano/covid19#6]
★data.jsonの準備ができたら

相談件数の表示ができるよう対応お願いします。

長野県のWebページの表記に合わせられたら、名称は変更した方が良いかなと。
https://www.pref.nagano.lg.jp/hoken-shippei/kenko/kenko/kansensho/joho/bukan-haien-doko.html

東京都版「新型コロナコールセンター相談件数」
　↓
長野県版「新型コロナウイルス感染症に関する相談件数」

**Comment by kikd** [comment]
とりあえずPR作成しておきました～

**Comment by tsuka39** [comment]
ありがとうございます！！
明日（日曜日）、data.json、整えます！
そしたら、公開できすはず、、
