### ISSUE TITLE
当サイトに関するお問い合わせ先の明記

### ISSUE THREAD

**Issue by ShinoharaTa** [Stop-COVID19-Nagano/covid19#61]
当サイトに関して、有志であるということが大々的には明記されていない。
サイトトップ、お知らせの上に枠を作り、融資であるということを明記する。
あわせて、お問い合わせ先について明記することを検討。
お問い合わせ先は、次のどちらかで検討しています。

・GitHub Issues
・Facebook Group

**Comment by wataruoguchi** [comment]
Facebook Groupだと流れていってしまうので問合せ先はissueがいいかと思います。

**Comment by ShinoharaTa** [comment]
お問合せ先を記載するにあたって、issueのお問い合わせテンプレート等作っていただくことって可能でしょうか。
しばらくはそれで運用してみようと思います。

掲載するにあたっての位置と文言はどのようにいたしましょうか。

位置はサイドメニュー下部あたりに
運営：〇〇（Facebook Groupへのリンク）
お問い合わせ：GitHub（GitHub Issueへのリンク）

という感じで掲載しようかと考えております

**Comment by kikd** [comment]
「当サイトについて」の中でいいんじゃないかなと思っています。
問い合わせ場所がわかりづらくなってしまう恐れがあるのが懸念事項ですが。。。

**Comment by ShinoharaTa** [comment]
試しに組んで、どこかで確認できるようにしてみます！

**Comment by ShinoharaTa** [comment]
これから実装しようと考えていましたが、GitHub issueだと要望や意見、提案の敷居が高く感じる人がいるかなと思いました。
またFacebook GroupだとFacebook恐怖症の人も多く・・・

いっそ、お問合せ先のMLを作成してメールアドレスの掲載できないでしょうか。
でもドメインどうするか等の問題はありますね・・・

**Comment by ShinoharaTa** [comment]
とりあえず組んでみました。
![image](https://user-images.githubusercontent.com/23314412/78916644-bf509a80-7ac8-11ea-9c71-59d1a83afdd2.png)

こちらでご確認いただけます。
https://shino3-test.netlify.com/

良さそうなので、一旦このままリリースの準備入ります
