### ISSUE TITLE
グラフ内の軽症、中等症、重症を入院中の中から削除

### ISSUE THREAD

**Issue by wataruoguchi** [Stop-COVID19-Nagano/covid19#63]
## 改善詳細 / Details of Improvement
- 長野県の発表しているデータには、入院中／退院のデータ区別はあるものの、入院中の患者の症状の度合いを示すものは出ていないはず。誤解を招くため、これらの項目を削除すべき。

## スクリーンショット / Screenshot
<img width="567" alt="Screen Shot 2020-04-04 at 1 26 28 AM" src="https://user-images.githubusercontent.com/8963743/78422359-87061380-7613-11ea-9513-76f97ee44623.png">

## 期待する見せ方・挙動 / Expected behavior
入院中を一つのセクションとし、子セクションを設けない。（死亡、退院と同じ見た目）

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kikd** [comment]
こちら着手します
