### ISSUE TITLE
ローカルリポジトリへPushする方法

### ISSUE THREAD

**Issue by ShinoharaTa** [Stop-COVID19-Nagano/covid19#76]
もしご存知でしたら教えてたいだきたいのですが、最新のdevelopブランチを自ブランチにマージするとPush時にエラーとなってしまいます。

![image](https://user-images.githubusercontent.com/23314412/78472782-8df96700-7776-11ea-9b37-dc755a01f09e.png)
内容からしてPermissionっぽいんのですが、なにかご存知でしたら教えていただけると。
よろしくおねがいします

**Comment by kikd** [comment]
ツールの認証情報を更新するのは試してみたでしょうか？
https://github.community/t5/GitHub-Actions/Refusing-to-allow-an-integration-to-create-or-update/td-p/32472

**Comment by ShinoharaTa** [comment]
GitHub Actionって最近追加されてたのですね・・・。WEB上ででPermissionいじれなくてちょっとめんどくさかったですが、解決しました。
対処方法としてピン留めしておくなどいかがでしょうか・・・？

**Comment by ShinoharaTa** [comment]
GitHub Actionを使用している関係上、Pushするときに権限がないときにこのメッセージが表示される。
一度、GitのアプリケーションとGitHubのOAuth認証を解除し、再度連携することで使用可能となる
