### ISSUE TITLE
「最新のお知らせ」表示領域の見直し

### ISSUE THREAD

**Issue by kikd** [Stop-COVID19-Nagano/covid19#77]
## 改善詳細 / Details of Improvement
- 長野県のサイトで表示される新着情報が最新5件までとなったため、PC版のサイトを見ると余白ができています。
#25 で行ったscrollable対応を見直す必要ありそうです。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/5682821/78472935-bb92e000-7777-11ea-8853-41d05b1c3891.png)

## 期待する見せ方・挙動 / Expected behavior
- 最新のお知らせの余白が表示されない

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kikd** [comment]
https://github.com/Stop-COVID19-Nagano/covid19/blob/505fb9b921fcf59311e37b67370c1f8834b5cd09/components/WhatsNew.vue#L65
このheightをmax-heightに変えればいいと思ってます。

スマートフォンで5件表示すると結構画面が占められてしまうので、scrollableは残したいと考えています。

**Comment by ShinoharaTa** [comment]
最新のお知らせ取得時はnews.jsonは全件置き換えとなるイメージでしょうか。
可能なら、過去のお知らせ一覧も保持したまま、トップページの表示件数は絞ってみてはと考えておりました。

**Comment by kikd** [comment]
ビルド時にデータを取得する仕組みに変わったので、過去のお知らせ一覧を保持する案は厳しいのではと思います。

**Comment by kikd** [comment]
> ビルド時にデータを取得する仕組みに変わったので、過去のお知らせ一覧を保持する案は厳しいのではと思います。

news.jsonも全件置き換わります。
