### ISSUE TITLE
陽性患者数のグラフ縦軸の数字を整数にしたい

### ISSUE THREAD

**Issue by kikd** [Stop-COVID19-Nagano/covid19#8]
## 改善詳細 / Details of Improvement
- 陽性患者数のグラフ縦軸の表示が小数表示になっている。  
  患者数が1.2人や1.5人という単位にはならない。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/5682821/77221033-40330b00-6b89-11ea-9f20-c046de596fbe.png)

## 期待する見せ方・挙動 / Expected behavior
- 縦軸に小数が表示されない

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

## --edit--
東京都版では最初から人数が多かったので、こういうケースが起きていなかったと推察。。

**Comment by kikd** [comment]
グラフの表示にはChart.jsを使っているので、そちらのドキュメントを見れば解決するはず

**Comment by kikd** [comment]
https://www.chartjs.org/docs/latest/axes/cartesian/linear.html
これのstepSizeっぽい

stepSizeを1にするとこんな感じになるけど、これはアリなんだろうか
![image](https://user-images.githubusercontent.com/5682821/77227600-c6b90e00-6bc4-11ea-9163-5d9bef8ebb49.png)

**Comment by tsuka39** [comment]
悩ましいですね、、、
見た目は今の方がいい感じだけど、値的には修正版の方が正しいと私は思います。。

**Comment by hisayan** [comment]
suggestedMin を 5 とか 10 にしておいたら、見た感じは、すこし落ち着くかもしれないですね。
※見た目って、個人の好みもありそうですが。それぞれの好きで、すすめましょう!
