### ISSUE TITLE
「最新のお知らせ」のリンクから長野県のサイトに移動しない

### ISSUE THREAD

**Issue by kikd** [Stop-COVID19-Nagano/covid19#81]
## 改善詳細 / Details of Improvement
- 最新のお知らせのリンクが相対パスになっており、長野県のサイトに移動しません。
長野県側のサイトがリニューアルした際に、リンクが相対パスに変わったことが原因となっていそうです。
![image](https://user-images.githubusercontent.com/5682821/78523420-acf60880-780b-11ea-9a51-c1cd654ac053.png)

[スクレイパー側](https://github.com/wataruoguchi/covid19_nagano_scraper/issues/2)に別途issueを作成してます。

## スクリーンショット / Screenshot

外部サイトを示すアイコンが表示されておらず
![image](https://user-images.githubusercontent.com/5682821/78523513-04947400-780c-11ea-94f5-7b7ef581c464.png)

リンクをクリックすると404エラーとなります。
![image](https://user-images.githubusercontent.com/5682821/78523471-e0d12e00-780b-11ea-83bd-8af9e1ad1e2f.png)

## 期待する見せ方・挙動 / Expected behavior
- リンクをクリックすると長野県のサイトに移動できる

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

ひとまず、こちらでの対応は不要という認識です。

**Comment by wataruoguchi** [comment]
@kikd こちらでも、ありがとうございました。development を master に反映する、等 master への何らかのpushで新しいデータが取り込まれてビルドされると思います。

**Comment by kikd** [comment]
修正ありがとうございました。development版でも治っていること確認できました。
本番環境でも確認できたらcloseしたいと思います。

**Comment by kikd** [comment]
![image](https://user-images.githubusercontent.com/5682821/78622999-94482a00-78c1-11ea-8a5f-ad62387e0e34.png)

本番環境でも確認できました！
