### ISSUE TITLE
陽性患者の属性の日付処理に失敗している

### ISSUE THREAD

**Issue by ShinoharaTa** [Stop-COVID19-Nagano/covid19#92]
## 起こっている問題 / The Problem
- 陽性患者の公表日が正常に表示されていない

## スクリーンショット / Screenshot
![Screenshot_20200408-015935_Chrome](https://user-images.githubusercontent.com/23314412/78698151-d3679100-793c-11ea-872d-16252d3cd05f.jpg)

## 期待する見せ方・挙動 / Expected Behavior
- 日付が表示されること

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by wataruoguchi** [comment]
日付データに全角数字が入っていたことによるもの。修正済です。

<img width="565" alt="Screen Shot 2020-04-07 at 11 33 25 AM" src="https://user-images.githubusercontent.com/8963743/78706275-a88d2680-78c3-11ea-9cfd-36264abab909.png">
