### ISSUE TITLE
ドメイン変更に伴う、コード内のURL変更

### ISSUE THREAD

**Issue by ShinoharaTa** [Stop-COVID19-Nagano/covid19#93]
## 改善詳細 / Details of Improvement
stop-covid19-nagano.netlify.com → nagano.stopcovid19.jp に変更する

## スクリーンショット / Screenshot
なし

## 期待する見せ方・挙動 / Expected behavior
netlifyのドメインを使用せず、stopcovid19.jpドメインに移行されること。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kikd** [comment]
こちら未着手ならやろうと思います。

**Comment by kikd** [comment]
併せてfacebookのogpも修正必要そうでしょうか？

**Comment by ShinoharaTa** [comment]
ざっと見る限り、対象箇所は以下の通りかと思います。
（ディレクトリ内をGrepした感じです）

- nuxt.config.ts 内のOGP
- README.md 内のURL
- print.vue 内のURL

**Comment by kikd** [comment]
対象箇所の確認ありがとうございます！
